-- WINE-59: e-postverifiering. Idempotent (samma satser som körs vid varje
-- appstart via schema.sql). ORDNING: backfill av befintliga konton till
-- verifierade INNAN NOT NULL sätts. Endast rader som ännu är NULL berörs, så
-- ett senare omkörande rör aldrig ett medvetet overifierat (false) konto.
-- Ingen mail skickas och ingen formatvalidering görs retroaktivt.

BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified boolean;
UPDATE users SET email_verified = true WHERE email_verified IS NULL;
ALTER TABLE users ALTER COLUMN email_verified SET DEFAULT false;
ALTER TABLE users ALTER COLUMN email_verified SET NOT NULL;

CREATE TABLE IF NOT EXISTS user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    purpose varchar(255) NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    UNIQUE (user_id, purpose)
);
CREATE INDEX IF NOT EXISTS user_tokens_user_id_idx ON user_tokens (user_id);

COMMIT;
