-- WINE-59: e-postverifiering. Idempotent (samma satser som körs vid varje
-- appstart via schema.sql). ORDNING: backfill av befintliga konton till
-- verifierade INNAN NOT NULL sätts. Endast rader som ännu är NULL berörs, så
-- ett senare omkörande rör aldrig ett medvetet overifierat (false) konto.
-- Ingen mail skickas och ingen formatvalidering görs retroaktivt.

BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified boolean;
UPDATE users SET email_verified = true WHERE email_verified IS NULL;
ALTER TABLE users ALTER COLUMN email_verified SET DEFAULT false;
ALTER TABLE users ALTER COLUMN email_verified SET NOT NULL;

-- Ett token per användare och syfte: UNIQUE (user_id, purpose). Tabellen kan redan ha skapats av
-- Hibernate (ddl-auto: update) från en tidigare version av grenen, med ett Hibernate-namngivet
-- UK_-constraint, en kolumn pending_password_hash eller ett partiellt unikt index (alla övergivna
-- varianter, ADR 0026). Därför: släpp det partiella indexet och kolumnen om de finns, rensa
-- eventuella dubbletter (behåll det nyaste), och lägg till constrainten bara om INGET unikt
-- constraint över (user_id, purpose) redan finns (uppslag i pg_constraint, oavsett namn).
-- Idempotent.
CREATE TABLE IF NOT EXISTS user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    purpose varchar(255) NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    UNIQUE (user_id, purpose)
);
DROP INDEX IF EXISTS user_tokens_one_reset_per_user;
ALTER TABLE user_tokens DROP COLUMN IF EXISTS pending_password_hash;
DELETE FROM user_tokens t USING user_tokens n WHERE t.user_id = n.user_id AND t.purpose = n.purpose AND t.id < n.id;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        WHERE c.conrelid = 'user_tokens'::regclass AND c.contype = 'u'
          AND (SELECT array_agg(a.attname::text ORDER BY a.attname::text)
               FROM unnest(c.conkey) AS k(attnum)
               JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum)
              = ARRAY['purpose', 'user_id']
    ) THEN
        ALTER TABLE user_tokens ADD CONSTRAINT user_tokens_user_id_purpose_key UNIQUE (user_id, purpose);
    END IF;
END
$$;
CREATE INDEX IF NOT EXISTS user_tokens_user_id_idx ON user_tokens (user_id);

COMMIT;
