package com.example.winecellar.infrastructure;

import com.example.winecellar.support.SharedPostgres;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * WINE-59: migreringen som markerar ALLA befintliga konton som verifierade.
 * En färsk, tom testdatabas bevisar ingenting här (UPDATE ... WHERE IS NULL är
 * då ett no-op - se CLAUDE.md om migreringsordning), så testet bygger i en
 * egen scratch-databas en users-tabell i det GAMLA formatet (utan
 * email_verified), med riktiga rader, och kör den fristående migreringen mot
 * den. Verifierar både att backfillen sker FÖRE NOT NULL (annars kraschar
 * migreringen mot de gamla raderna) och att en omkörning är ofarlig för ett
 * medvetet overifierat konto.
 */
class EmailVerificationMigrationIT extends SharedPostgres {

    private static final Path MIGRATION = Path.of("db/migrations/2026-10-09-add-email-verification.sql");

    @Test
    void skaMarkeraBefintligaKontonSomVerifieradeUtanAttRöraEttNyttOverifieratKonto() throws Exception {
        try (Connection admin = POSTGRES.createConnection("");
             Statement statement = admin.createStatement()) {
            statement.execute("DROP DATABASE IF EXISTS migration_wine59");
            statement.execute("CREATE DATABASE migration_wine59");
        }
        String url = POSTGRES.getJdbcUrl().replaceFirst("/[^/?]+(\\?|$)", "/migration_wine59$1");
        try (Connection connection = java.sql.DriverManager.getConnection(
                url, POSTGRES.getUsername(), POSTGRES.getPassword());
             Statement statement = connection.createStatement()) {
            // Gammalt tillstånd: users som den såg ut före WINE-59, med riktiga rader.
            statement.execute("""
                    CREATE TABLE users (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username varchar(255) NOT NULL UNIQUE,
                        password_hash varchar(255) NOT NULL,
                        created_at timestamptz NOT NULL,
                        default_min_quantity_filter integer NOT NULL DEFAULT 1,
                        own_rating_from_scale boolean NOT NULL DEFAULT false,
                        is_admin boolean NOT NULL DEFAULT false,
                        last_login_at timestamptz NOT NULL DEFAULT now()
                    )""");
            statement.execute("""
                    INSERT INTO users (username, password_hash, created_at) VALUES
                    ('Testus', 'hash1', now()), ('gammal-admin', 'hash2', now()), ('anna@example.com', 'hash3', now())""");

            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION));

            assertThat(count(statement, "select count(*) from users where email_verified = true")).isEqualTo(3);
            assertThat(count(statement, "select count(*) from users where email_verified = false")).isZero();
            assertThat(count(statement, "select count(*) from information_schema.columns where table_name = 'users' "
                    + "and column_name = 'email_verified' and is_nullable = 'NO' and column_default = 'false'"))
                    .isEqualTo(1);

            // Ett nytt konto är overifierat (false uttryckligen, som Hibernate sätter det).
            statement.execute("INSERT INTO users (username, password_hash, created_at, email_verified) "
                    + "VALUES ('ny@example.com', 'hash4', now(), false)");

            // Omkörning (schema.sql kör samma satser vid varje appstart) rör inte det kontot.
            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION));

            assertThat(count(statement,
                    "select count(*) from users where username = 'ny@example.com' and email_verified = false"))
                    .isEqualTo(1);
            assertThat(count(statement, "select count(*) from users where email_verified = true")).isEqualTo(3);
            assertThat(count(statement, "select count(*) from information_schema.tables "
                    + "where table_name = 'user_tokens'")).isEqualTo(1);
        }
    }

    @Test
    void schemaSqlSkaBackfillaFöreNotNullPåSammaSättSomMigreringen() throws Exception {
        String schema = Files.readString(Path.of("src/main/resources/schema.sql"));
        int add = schema.indexOf("ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified boolean;;");
        int backfill = schema.indexOf("UPDATE users SET email_verified = true WHERE email_verified IS NULL;;");
        int notNull = schema.indexOf("ALTER TABLE users ALTER COLUMN email_verified SET NOT NULL;;");
        assertThat(add).isPositive();
        assertThat(backfill).isGreaterThan(add);
        assertThat(notNull).isGreaterThan(backfill);
    }

    private static int count(Statement statement, String sql) throws Exception {
        try (ResultSet rs = statement.executeQuery(sql)) {
            rs.next();
            return rs.getInt(1);
        }
    }
}
